# GoReleaser config for ksc-agent
# Run: goreleaser release --clean
# Test: goreleaser build --snapshot --clean

version: 2

project_name: ksc-agent

before:
  hooks:
    - go mod tidy

builds:
  - id: ksc-agent
    main: ./cmd/ksc-agent
    binary: ksc-agent
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/kubestellar/console/pkg/agent.Version={{.Version}}

archives:
  - id: ksc-agent
    builds:
      - ksc-agent
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

# Homebrew tap - only runs if HOMEBREW_TAP_TOKEN is set
brews:
  - name: ksc-agent
    # Skip if token is not set
    skip_upload: '{{ if .Env.HOMEBREW_TAP_TOKEN }}false{{ else }}true{{ end }}'
    repository:
      owner: kubestellar
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/kubestellar/console"
    description: "Local agent for KubeStellar Console - bridges browser to kubeconfig and Claude Code"
    license: "Apache-2.0"
    test: |
      system "#{bin}/ksc-agent", "--version"
    install: |
      bin.install "ksc-agent"

release:
  github:
    owner: kubestellar
    name: console
  # Use RELEASE_NAME env var if set, otherwise fall back to tag
  name_template: "{{ if .Env.RELEASE_NAME }}{{ .Env.RELEASE_NAME }}{{ else }}{{ .Tag }}{{ end }}"
  draft: false
  prerelease: auto
